name: Build macOS

on:
  workflow_dispatch:
    inputs:
      signing-identity:
        description: 'Signing identity (e.g. "Developer ID Application: Your Name (TEAMID)")'
        required: true
      maven-profile:
        description: 'Maven profile to activate'
        required: true
        default: 'macosx-aarch64'
        type: choice
        options:
          - macosx-aarch64
          - macosx-x86_64

env:
  JAVA_VERSION: 17

jobs:
  build_macos:
    name: Build and Sign macOS App
    runs-on: ${{ inputs.maven-profile == 'macosx-aarch64' && 'macos-14' || 'macos-13' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          distribution: 'temurin'


      - name: Build app image
        run: mvn -B -DskipTests -Dmaven.javadoc.skip=true -P${{ inputs.maven-profile }},all package

      - name: Build jlink runtime
        run: |
          $JAVA_HOME/bin/jlink \
            --module-path target/classes:target/mods:target/libs \
            --add-modules java.desktop,java.base,java.logging,java.xml,java.scripting,java.compiler,java.instrument,jdk.unsupported,javafx.base,javafx.graphics,javafx.controls,javafx.fxml,java.sql,java.naming \
            --output target/runtime \
            --strip-native-commands \
            --strip-java-debug-attributes \
            --no-header-files \
            --no-man-pages \
            --ignore-signing-information \
            --compress=zip-6

      - name: Build jpackage app image
        run: |
          $JAVA_HOME/bin/jpackage \
            --type app-image \
            --name Dr.Rename \
            --runtime-image target/runtime \
            --module drrename/drrename.Launcher \
            --module-path target/classes:target/mods:target/libs \
            --dest target/jpackage \
            --icon dist/mac/drrename.icns \
            --mac-package-identifier com.drrename
